---
name: 🚀 Feature Request
description: Request a new feature.
title: 🚀 <title>
labels:
  - "type: feature request 🚀"
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the feature you're interested in.
      placeholder: Describe in a few lines your feature request.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested Solution
      description: |
        Describe the solution you'd like.
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
    validations:
      required: false
