---
collections:
  - name: ansible.posix
    version: 2.0.0

  - name: community.crypto
    version: 2.22.3

  - name: community.general
    version: 10.0.1

  - name: kubernetes.core
    version: 5.0.0
