---
collections:
  - name: ansible.posix
    version: 1.5.4

  - name: community.crypto
    version: 2.20.0

  - name: community.general
    version: 9.1.0

  - name: kubernetes.core
    version: 5.0.0
