---
collections:
  - name: ansible.posix
    version: 2.1.0

  - name: ansible.windows
    version: 3.3.0

  - name: community.crypto
    version: 3.1.0

  - name: community.docker
    version: 5.0.5

  - name: community.general
    version: 12.2.0

  - name: community.windows
    version: 3.1.0

  - name: kubernetes.core
    version: 6.2.0
