---
collections:
  - name: ansible.posix
    version: 1.6.2

  - name: community.crypto
    version: 2.21.0

  - name: community.general
    version: 9.2.0

  - name: kubernetes.core
    version: 5.0.0
