---
collections:
  - name: ansible.posix
    version: 2.1.0

  - name: ansible.windows
    version: 3.3.0

  - name: community.crypto
    version: 3.0.4

  - name: community.docker
    version: 4.8.2

  - name: community.general
    version: 11.4.0

  - name: community.windows
    version: 3.0.1

  - name: kubernetes.core
    version: 6.2.0
