---
collections:
  - name: ansible.posix
    version: 2.1.0

  - name: ansible.windows
    version: 3.2.0

  - name: community.crypto
    version: 3.0.2

  - name: community.docker
    version: 4.6.2

  - name: community.general
    version: 11.1.1

  - name: community.windows
    version: 3.0.1

  - name: kubernetes.core
    version: 6.2.0
