---
collections:
  - name: ansible.posix
    version: 1.5.4

  - name: community.crypto
    version: 2.21.0

  - name: community.general
    version: 10.0.1

  - name: kubernetes.core
    version: 5.0.0
